### ISSUE TITLE
Current version unable to find the Crude Oil Entity

### ISSUE THREAD

**Issue by hurricup** [tburrows13/FactorySearch#30]
It did work before I did update the mod. Can't say what was the previous version. 

Atm it just says - nothing found.

**Comment by tburrows13** [comment]
Thanks, fixed in 1.14.1 (dfd88afba795e70d93557f885ad264c689ed0ccd)

**Comment by hurricup** [comment]
Still does not work (properly) in 1.14.3, works only if 'all qualities' is checked
